#if !canImport(ObjectiveC)
import XCTest

extension CloudKitKeyValueStoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CloudKitKeyValueStoreTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CloudKitKeyValueStoreTests.__allTests__CloudKitKeyValueStoreTests),
    ]
}
#endif
